repos:
  - name: UADY
    oai_baseurl: "http://redi.uady.mx/oai/request"
    prefixes: ["oai_dc"]
    harvest_window_days: 0
    concurrency_per_host: 2
    max_bytes_pdf: 30000000
    allowed_mime:
      - application/pdf                                                           # pdf
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document   # word
      - application/vnd.openxmlformats-officedocument.presentationml.presentation # .pptx
      - text/plain
